module.exports = {
  content: ["*.html", "**/*.html", "**/*.js", "**/*.jsx", "**/*.ts", "**/*.tsx"],
  css: ["assets/css/main.css"],
  output: "assets/css/main.purged.css",
  safelist: [
    /^navbar/,
    /^nav-/,
    /^collapse/,
    /^burger-icon/,
    /^d-/,
    /^fs-/,
    /^text-/,
    /^bg-/,
    /^mt-/,
    /^mb-/,
    /^my-/,
    /^mx-/,
    /^p-/,
    /^pt-/,
    /^pb-/,
    /^py-/,
    /^px-/,
    /^border/,
    /^rounded/,
    /^position-/,
    /^align-/,
    /^justify-/,
    /^flex-/,
    /^w-/,
    /^h-/,
    /^z-/,
    /^swiper-/,
    /^card-/,
    /^btn-/,
    /^icon-/,
    /^form-/,
    /^section-/,
    /^animate__/,
    /^aos-/,
    /^fa-/,
    /^ri-/,
  ],
  defaultExtractor: (content) => content.match(/[\w-/:]+(?<!:)/g) || [],
};
